# -*- coding: utf-8 -*-
"""Spark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJ21J8Vu9pjD3431tiPXnLBsAT9uCxTk
"""

!pip install -q diffusers transformers accelerate safetensors huggingface_hub
!pip install -q --upgrade pillow
!pip install -q realesrgan

from huggingface_hub import notebook_login
notebook_login()

from diffusers import StableDiffusionPipeline
import torch

model_id = "gsdf/Counterfeit-V2.5"
pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    use_auth_token=True
).to("cuda" if torch.cuda.is_available() else "cpu")

pipe.enable_attention_slicing()
try:
    pipe.enable_xformers_memory_efficient_attention()
    print("xFormers enabled")
except:
    print("xFormers not available")

print("Model loaded successfully!")

from PIL import Image

def generate_image(prompt: str, height=512, width=512, steps=40, guidance=7.5):
    """
    توليد صورة واقعية من النص
    """
    image = pipe(prompt, height=height, width=width,
                 num_inference_steps=steps, guidance_scale=guidance).images[0]
    return image

from IPython.display import display

prompt = "شخصية المؤسس جالس على عرش ملكي، زي سعودي رسمي، إضاءة درامية، تفاصيل ذهبية وزخارف عربية، hyper realistic, cinematic lighting, high detail, 8k"
img = generate_image(prompt)
display(img)
img.save("saudi_founder.png")
print("Saved as saudi_founder.png")

import gradio as gr

def infer(prompt):
    img = generate_image(prompt)
    return img

iface = gr.Interface(fn=infer,
                     inputs=gr.Textbox(lines=2, placeholder="مثال: شخصية المؤسس جالس على العرش..."),
                     outputs="image",
                     title="مولد تصميمات AI")
iface.launch(share=True)

